### ISSUE TITLE
Add Chakra shell to Windows tests

### ISSUE THREAD

**Issue by tschneidereit** [h4writer/arewefastyet#42]
@evilpie wrote [a shell host for IE's Chakra engine](https://github.com/evilpie/chakra-shell) a year ago. Would be nice to run the AWFY tests in that, too.

**Comment by h4writer** [comment]
Actually the windows machine is running full browsers, so we could just run the IE browser. Though not sure how interesting it would be. AWFY is used for regression testing and performance tracking of nightly builds. Not to have final benchmarks results of release builds. So we would run tests on a browser that we know will give the same results the whole time. (because there is no changes/improvements in between runs) ...

**Comment by tschneidereit** [comment]
Hum, that is a pretty good point :) I guess I'd just like to see how it compares, but you're right, there's absolutely no need to test that over and over again. Until MS decide to release nightly builds, that is :) Closing for now.
