### ISSUE TITLE
Add Chackra

### ISSUE THREAD

**Issue by NoNameProvided** [h4writer/arewefastyet#96]
Chakra is opensourced now, it would be nice to see how it compares to SpiderMonkey and V8

**Comment by h4writer** [comment]
None of the windows machines have currently a developer environment. They all fetch binaries online. though we have edge running on: https://arewefastyet.com/#machine=31

So we can see the performance already. I don't think there are up to date binaries of the shell compiled somewhere that I can fetch. That would be awesome to add. Since currently updating Edge is done manually...
